name: .NET Core

on:
  push:
    branches: [Version - 1.0]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.700
    - name: Install dependencies
      run: dotnet restore
      working-directory: Backend/CardsAPI
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: Backend/CardsAPI
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      working-directory: Backend/CardsAPI/CardsAPITests
