name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.1.0
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.700
    - name: Install dependencies
      run: dotnet restore
      working-directory: Backend/CardsAPI
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: Backend/CardsAPI
    - name: Test
      run: dotnet test --verbosity normal
      working-directory: Backend/CardsAPITests/
