name: .NET Core

on:
  push:
    branches: [ master ]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2.1.0
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.700
    - name: Install dependencies
      working-directory: Backend/CardsAPI/
      run: dotnet restore
    - name: Build with dotnet
      working-directory: Backend/CardsAPI/
      run: dotnet build --configuration Release      
    - name: Run tests
      working-directory: Backend/CardsAPI/CardsAPITests
      run: dotnet test --configuration Release
    - name: Coverage check
      uses: devmasx/coverage-check-action@v1.1.0
      result_path: coverage/example.lcov

      
